server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ${KEYCLOAK_CLIENT_ID:gateapp}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:zgLpg32jFz18O4kY47kSERrsbWlO1Qoh}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            authorization-uri: ${KEYCLOAK_AUTHORIZATION_URI:http://localhost:8180/realms/keysec/protocol/openid-connect/auth}
            token-uri: ${KEYCLOAK_TOKEN_URI:http://localhost:8180/realms/keysec/protocol/openid-connect/token}
            jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/keysec/protocol/openid-connect/certs}
            user-info-uri: ${KEYCLOAK_USER_INFO_URI:http://localhost:8180/realms/keysec/protocol/openid-connect/userinfo}
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/keysec/protocol/openid-connect/certs}

  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - TokenRelay
          routes:
            - id: flow-manager
              uri: lb://flow-manager
              predicates:
                - Path=/api/v1/files,/api/v1/files/**
          httpclient:
            connect-timeout: ${GATEWAY_CONNECT_TIMEOUT_MS:5000}
            response-timeout: ${GATEWAY_RESPONSE_TIMEOUT:60s}

  webflux:
    multipart:
      max-in-memory-size: ${MAX_FILE_SIZE:200MB}
      max-disk-usage-per-part: ${MAX_FILE_SIZE:200MB}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
    register-with-eureka: ${EUREKA_REGISTER_WITH_EUREKA:true}
    fetch-registry: ${EUREKA_FETCH_REGISTRY:true}
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:true}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}


management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      probes:
        enabled: true
